import type { FormEvent } from "react";

import type { LoanInput, LoanRecord } from "../../main/db/repositories/finance-repository";

export function LoanEditor({ loan, onSave, onCancel }: { loan?:LoanRecord|null;onSave:(input:LoanInput)=>void|Promise<void>;onCancel:()=>void }) {
  async function submit(event:FormEvent<HTMLFormElement>) { event.preventDefault();const form=new FormData(event.currentTarget);await onSave({lender:String(form.get("lender")),kind:String(form.get("kind")) as LoanInput["kind"],classification:String(form.get("classification")) as LoanInput["classification"],principal:Number(form.get("principal")),outstandingBalance:Number(form.get("outstandingBalance")),interestRateBasisPoints:Math.round(Number(form.get("interestRate"))*100),startDate:String(form.get("startDate")),dueDate:String(form.get("dueDate")||"")||null,repaymentFrequency:String(form.get("repaymentFrequency")) as LoanInput["repaymentFrequency"],installmentAmount:Number(form.get("installmentAmount"))||null,termMonths:Number(form.get("termMonths"))||null,notes:String(form.get("notes")||"")||null}); }
  return <form className="expense-editor" onSubmit={submit}>
    <label className="field-group"><span>Lender</span><input defaultValue={loan?.lender} name="lender" required/></label>
    <div className="form-grid-two"><label className="field-group"><span>Loan type</span><select defaultValue={loan?.kind} name="kind"><option value="bank">Bank loan</option><option value="non_bank">Non-bank loan</option><option value="interest_free">Interest-free family/friend loan</option></select></label><label className="field-group"><span>Classification</span><select defaultValue={loan?.classification} name="classification"><option value="current">Under 12 months</option><option value="non_current">Over 12 months</option></select></label></div>
    <div className="form-grid-two"><label className="field-group"><span>Original principal</span><input defaultValue={loan?.principal} name="principal" type="number" min="0" required/></label><label className="field-group"><span>Outstanding balance</span><input defaultValue={loan?.outstandingBalance} name="outstandingBalance" type="number" min="0" required/></label></div>
    <div className="form-grid-two"><label className="field-group"><span>Interest rate (%)</span><input name="interestRate" type="number" min="0" step="0.01" defaultValue={(loan?.interestRateBasisPoints??0)/100}/></label><label className="field-group"><span>Start date</span><input defaultValue={loan?.startDate} name="startDate" type="date" required/></label></div>
    <div className="form-grid-two"><label className="field-group"><span>Repayment frequency</span><select defaultValue={loan?.repaymentFrequency??"monthly"} name="repaymentFrequency"><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annually">Annually</option><option value="custom">Custom</option></select></label><label className="field-group"><span>Installment amount</span><input defaultValue={loan?.installmentAmount??""} name="installmentAmount" type="number" min="1"/></label></div>
    <div className="form-grid-two"><label className="field-group"><span>Term (months)</span><input defaultValue={loan?.termMonths??""} name="termMonths" type="number" min="1"/></label><label className="field-group"><span>Due date</span><input defaultValue={loan?.dueDate??""} name="dueDate" type="date"/></label></div><label className="field-group"><span>Notes</span><textarea defaultValue={loan?.notes??""} name="notes"/></label>
    <div className="unit-form-actions"><button className="primary-button">{loan?"Save changes":"Save loan"}</button><button className="secondary-button" onClick={onCancel} type="button">Cancel</button></div>
  </form>;
}
