import type Database from "better-sqlite3-multiple-ciphers";
import { ugx } from "../../../domain/money";
import { calculateMonthlyRentalTaxProvision } from "../../../domain/rental-tax";
import { createFinanceRepository } from "./finance-repository";

export type DashboardTarget="bookings"|"payments"|"expenses"|"staff"|"financial-position";
export interface TodayOverview {
  date:string;month:string;occupancyPercent:number;collected:number;outstanding:number;netPosition:number;
  expenses:number;staffDue:number;taxProvision:number;
  agenda:{id:string;type:"arrival"|"departure";customerName:string;unitName:string;time:string;balance:number}[];
  units:{id:string;name:string;status:"occupied"|"arriving"|"checkoutDue"|"available";guestName:string|null}[];
  warnings:{id:string;label:string;detail:string;target:DashboardTarget}[];
}
const datePattern=/^\d{4}-\d{2}-\d{2}$/;
export function createDashboardRepository(database:Database.Database,businessId:string){
 return Object.freeze({getToday(date:string):TodayOverview{if(!datePattern.test(date)||new Date(`${date}T00:00:00Z`).toISOString().slice(0,10)!==date)throw new Error("Choose a valid dashboard date.");const month=date.slice(0,7);const report=createFinanceRepository(database,businessId).getMonthlyReport(month);
  const activeUnits=database.prepare<[string],{count:number}>("SELECT COUNT(*) count FROM units WHERE business_id=? AND status='active' AND archived_at IS NULL").get(businessId)?.count??0;const days=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).getUTCDate();const nights=database.prepare<[string,string],{total:number}>(`SELECT COALESCE(SUM(bm.occupied_nights * CASE WHEN b.occupancy_mode='one_room' THEN 0.5 ELSE 1 END),0) total FROM booking_months bm JOIN bookings b ON b.id=bm.booking_id WHERE b.business_id=? AND bm.month=? AND b.status<>'cancelled' AND b.archived_at IS NULL`).get(businessId,month)?.total??0;
  const movements=database.prepare<[string,string],{collected:number}>(`SELECT COALESCE(SUM(CASE WHEN direction='receipt' THEN amount WHEN direction='refund' THEN -amount ELSE 0 END),0) collected FROM payments WHERE business_id=? AND substr(paid_at,1,7)=?`).get(businessId,month)?.collected??0;
  const outstanding=database.prepare<[string],{total:number}>(`SELECT COALESCE(SUM(MAX(0,b.total_amount-COALESCE((SELECT SUM(CASE WHEN direction='receipt' THEN amount WHEN direction='refund' THEN -amount ELSE 0 END) FROM payments p WHERE p.booking_id=b.id),0))),0) total FROM bookings b WHERE b.business_id=? AND b.status<>'cancelled' AND b.archived_at IS NULL`).get(businessId)?.total??0;
  const expenses=database.prepare<[string,string],{total:number}>("SELECT COALESCE(SUM(amount),0) total FROM expenses WHERE business_id=? AND substr(expense_date,1,7)=? AND archived_at IS NULL").get(businessId,month)?.total??0;
  const staffDue=database.prepare<[string,string],{total:number}>("SELECT COALESCE(SUM(MAX(0,earned_amount+adjustment-paid_amount)),0) total FROM staff_earnings WHERE business_id=? AND month=?").get(businessId,month)?.total??0;
  const taxRate=database.prepare<[string,string],{amount:number}>("SELECT amount_per_unit amount FROM tax_provision_rates WHERE business_id=? AND effective_from<=? AND archived_at IS NULL ORDER BY effective_from DESC LIMIT 1").get(businessId,`${month}-01`)?.amount??600000;
  const bookingRows=database.prepare<[string,string,string,string],any>(`SELECT b.id,b.check_in,b.check_out,b.check_in_time,b.check_out_time,b.total_amount,c.name customer_name,u.name unit_name,COALESCE((SELECT SUM(CASE WHEN direction='receipt' THEN amount WHEN direction='refund' THEN -amount ELSE 0 END) FROM payments p WHERE p.booking_id=b.id),0) paid FROM bookings b JOIN customers c ON c.id=b.customer_id JOIN units u ON u.id=b.unit_id WHERE b.business_id=? AND (b.check_in=? OR b.check_out=?) AND b.status<>'cancelled' AND b.archived_at IS NULL ORDER BY CASE WHEN b.check_out=? THEN 0 ELSE 1 END,u.name`).all(businessId,date,date,date);
  const agenda:TodayOverview["agenda"]=bookingRows.map((row:any)=>({id:row.id,type:row.check_out===date?"departure" as const:"arrival" as const,customerName:row.customer_name,unitName:row.unit_name,time:row.check_out===date?row.check_out_time:row.check_in_time,balance:Math.max(0,row.total_amount-row.paid)}));
  const units=database.prepare<[string],{id:string;name:string}>("SELECT id,name FROM units WHERE business_id=? AND status='active' AND archived_at IS NULL ORDER BY name").all(businessId).map((unit)=>{const booking=database.prepare<[string,string,string,string],any>(`SELECT b.check_in,b.check_out,c.name customer_name FROM bookings b JOIN customers c ON c.id=b.customer_id WHERE b.business_id=? AND b.unit_id=? AND b.check_in<=? AND b.check_out>=? AND b.status IN ('confirmed','checked_in','completed') AND b.archived_at IS NULL ORDER BY b.check_in LIMIT 1`).get(businessId,unit.id,date,date);if(!booking)return{...unit,status:"available" as const,guestName:null};return{...unit,status:booking.check_out===date?"checkoutDue" as const:booking.check_in===date?"arriving" as const:"occupied" as const,guestName:booking.customer_name};});
  const warnings:TodayOverview["warnings"]=[];for(const item of agenda.filter((item:any)=>item.balance>0&&item.type==="departure"))warnings.push({id:`balance:${item.id}`,label:`Balance due · ${item.customerName}`,detail:`${item.unitName} · UGX ${new Intl.NumberFormat("en-UG").format(item.balance)}`,target:"payments"});if(staffDue>0)warnings.push({id:"staff-due",label:"Staff allocation unpaid",detail:`UGX ${new Intl.NumberFormat("en-UG").format(staffDue)}`,target:"staff"});const recurring=database.prepare<[string,string],{count:number}>("SELECT COUNT(*) count FROM recurring_expenses WHERE business_id=? AND next_review_month<=? AND archived_at IS NULL").get(businessId,month)?.count??0;if(recurring)warnings.push({id:"recurring",label:"Recurring expenses need review",detail:`${recurring} template${recurring===1?"":"s"} due`,target:"expenses"});if(report.balanceSheet.difference!==0)warnings.push({id:"unbalanced",label:"Financial position is not balanced",detail:`UGX ${new Intl.NumberFormat("en-UG").format(Math.abs(report.balanceSheet.difference))} difference`,target:"financial-position"});
  return{date,month,occupancyPercent:activeUnits?Math.round(nights/(activeUnits*days)*100):0,collected:movements,outstanding,netPosition:report.incomeStatement.netIncome,expenses,staffDue,taxProvision:calculateMonthlyRentalTaxProvision(activeUnits,ugx(taxRate)),agenda,units,warnings};
 }});
}
