import { Landmark, PackageCheck, Plus, Scale, X } from "lucide-react";
import { useCallback, useEffect, useState, type FormEvent } from "react";

import type { BusinessUnit } from "../../domain/types";
import { calculateMonthlyRentalTaxProvision } from "../../domain/rental-tax";
import { ugx } from "../../domain/money";
import type { Supplier } from "../../main/db/repositories/expense-repository";
import type { AssetRecord, FinancialPosition, LoanRecord, PeriodClose } from "../../main/db/repositories/finance-repository";
import { IPC_CHANNELS, type IpcPayload } from "../../shared/ipc";
import { AssetEditor } from "../components/AssetEditor";
import { LoanEditor } from "../components/LoanEditor";
import { MonthEndQuestionnaire } from "../components/MonthEndQuestionnaire";

type View="position"|"assets"|"loans"|"month-end";type Panel="balance"|"inventory"|"asset"|"loan"|null;
const formatUgx=(value:number)=>`UGX ${new Intl.NumberFormat("en-UG").format(value)}`;
const monthNow=()=>new Date().toISOString().slice(0,7);
const categories=[
  ["cash_on_hand","Cash on hand"],["current_bank","Current bank"],["mobile_money","Mobile money"],["long_term_deposit","Deposit over one year"],["customer_receivable","Customer receivable"],["other_receivable","Other receivable"],["supplier_payable","Supplier payable"],["staff_payable","Staff payable"],["referral_payable","Referral payable"],["tax_payable","Taxes and fees due"],["pension_payable","Pension due"],["owner_capital","Owner capital"],["owner_drawings","Owner drawings"],
] as const;

export function FinancialPositionScreen({units,taxProvisionPerUnit}:{units:BusinessUnit[];taxProvisionPerUnit:number}) {
  const [month,setMonth]=useState(monthNow);const [view,setView]=useState<View>("position");const [panel,setPanel]=useState<Panel>(null);
  const [position,setPosition]=useState<FinancialPosition|null>(null);const [assets,setAssets]=useState<AssetRecord[]>([]);const [loans,setLoans]=useState<LoanRecord[]>([]);const [period,setPeriod]=useState<PeriodClose>({month:monthNow(),status:"open",reason:null});const [suppliers,setSuppliers]=useState<Supplier[]>([]);const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setError(null);const [overview,supplierResult]=await Promise.all([window.stayBooks.invoke(IPC_CHANNELS.FINANCE_OVERVIEW,{month}),window.stayBooks.invoke(IPC_CHANNELS.SUPPLIERS_LIST,{})]);if(!overview.ok)return setError(overview.message);setPosition(overview.data.position);setAssets(overview.data.assets);setLoans(overview.data.loans);setPeriod(overview.data.period);if(supplierResult.ok)setSuppliers(supplierResult.data);},[month]);
  useEffect(()=>{void load();},[load]);
  async function saveBalance(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const result=await window.stayBooks.invoke(IPC_CHANNELS.BALANCE_SAVE,{month,category:String(form.get("category")) as IpcPayload<typeof IPC_CHANNELS.BALANCE_SAVE>["category"],amount:Number(form.get("amount")),unitId:String(form.get("unitId")||"")||null,notes:String(form.get("notes")||"")||null});if(!result.ok)return setError(result.message);setPosition(result.data);setPanel(null);}
  async function saveInventory(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const result=await window.stayBooks.invoke(IPC_CHANNELS.INVENTORY_SAVE,{month,unitId:String(form.get("unitId")||"")||null,value:Number(form.get("value")),notes:String(form.get("notes")||"")||null});if(!result.ok)return setError(result.message);setPosition(result.data);setPanel(null);}
  async function saveAsset(input:IpcPayload<typeof IPC_CHANNELS.ASSET_CREATE>){const result=await window.stayBooks.invoke(IPC_CHANNELS.ASSET_CREATE,input);if(!result.ok){setError(result.message);throw new Error(result.message);}setAssets((list)=>[result.data,...list]);setPanel(null);await load();}
  async function saveLoan(input:IpcPayload<typeof IPC_CHANNELS.LOAN_CREATE>){const result=await window.stayBooks.invoke(IPC_CHANNELS.LOAN_CREATE,input);if(!result.ok){setError(result.message);throw new Error(result.message);}setLoans((list)=>[result.data,...list]);setPanel(null);await load();}
  async function close(){const result=await window.stayBooks.invoke(IPC_CHANNELS.PERIOD_CLOSE,{month});if(!result.ok)return setError(result.message);setPeriod(result.data);}
  async function reopen(reason:string){const result=await window.stayBooks.invoke(IPC_CHANNELS.PERIOD_REOPEN,{month,reason});if(!result.ok)return setError(result.message);setPeriod(result.data);}
  const activeUnits=units.filter(({status})=>status==="active").length;
  return <section className="financial-screen"><header className="payments-header"><div><h1>Financial Position</h1><p>Balances, obligations, loans, assets, equity, and month close.</p></div><div><label className="month-control"><span>Month</span><input type="month" value={month} onChange={(event)=>setMonth(event.target.value)}/></label><button className="primary-button compact-button" onClick={()=>setPanel("balance")}><Plus size={16}/>Add balance</button></div></header>
    <nav className="section-tabs" aria-label="Financial position views">{(["position","assets","loans","month-end"] as const).map((item)=><button data-active={view===item} key={item} onClick={()=>setView(item)}>{item==="month-end"?"Month-end":item[0].toUpperCase()+item.slice(1)}</button>)}</nav>
    {error?<p className="form-alert">{error}</p>:null}
    {view==="position"?<><div className="position-equation"><div><span>Total assets</span><strong>{formatUgx(position?.totalAssets??0)}</strong></div><Scale size={22}/><div><span>Liabilities + equity</span><strong>{formatUgx(position?.totalLiabilitiesAndEquity??0)}</strong></div><span className={`balance-state ${position?.balanced?"balanced":"unbalanced"}`}>{position?.balanced?"Balanced":`${formatUgx(Math.abs(position?.difference??0))} difference`}</span></div><div className="position-grid">{[["Cash and current accounts",position?.cashAndCurrentAccounts],["Long-term deposits",position?.longTermDeposits],["Receivables",position?.receivables],["Guest-supply inventory",position?.inventory],["Fixed assets",position?.fixedAssets],["Provider and other payables",position?.payables],["Loans",position?.loans],["Owner equity",position?.ownerEquity],["Monthly rental tax provision",calculateMonthlyRentalTaxProvision(activeUnits,ugx(taxProvisionPerUnit))]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{formatUgx(Number(value??0))}</strong></div>)}</div><button className="secondary-button compact-button" onClick={()=>setPanel("inventory")}><PackageCheck size={16}/>Inventory value</button></>:view==="assets"?<div className="statement-panel"><header className="panel-toolbar"><h2>Fixed asset register</h2><button className="primary-button compact-button" onClick={()=>setPanel("asset")}><Plus size={16}/>New asset</button></header><div className="table-scroll"><table className="statement-table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Scope</th><th>Amount</th></tr></thead><tbody>{assets.map((asset)=><tr key={asset.id}><td>{asset.purchaseDate}</td><td><strong>{asset.description}</strong></td><td>{asset.category}</td><td>{units.find(({id})=>id===asset.unitId)?.name??"Shared"}</td><td className="money-cell">{formatUgx(asset.purchaseAmount)}</td></tr>)}</tbody></table></div></div>:view==="loans"?<div className="statement-panel"><header className="panel-toolbar"><h2>Loan register</h2><button className="primary-button compact-button" onClick={()=>setPanel("loan")}><Plus size={16}/>New loan</button></header><div className="table-scroll"><table className="statement-table"><thead><tr><th>Lender</th><th>Type</th><th>Term</th><th>Principal</th><th>Outstanding</th></tr></thead><tbody>{loans.map((loan)=><tr key={loan.id}><td><strong>{loan.lender}</strong></td><td>{loan.kind.replace("_"," ")}</td><td>{loan.classification==="current"?"Under 12 months":"Over 12 months"}</td><td className="money-cell">{formatUgx(loan.principal)}</td><td className="money-cell">{formatUgx(loan.outstandingBalance)}</td></tr>)}</tbody></table></div></div>:<MonthEndQuestionnaire month={month} status={period.status} balanced={position?.balanced??false} onClose={()=>void close()} onReopen={(reason)=>void reopen(reason)}/>}
    {panel?<aside className="expense-side-panel"><header><h2>{panel==="balance"?"Record balance":panel==="inventory"?"Inventory value":panel==="asset"?"New asset":"New loan"}</h2><button className="icon-button" aria-label="Close panel" onClick={()=>setPanel(null)}><X size={17}/></button></header>{panel==="asset"?<AssetEditor units={units} suppliers={suppliers} onSave={saveAsset} onCancel={()=>setPanel(null)}/>:panel==="loan"?<LoanEditor onSave={saveLoan} onCancel={()=>setPanel(null)}/>:panel==="inventory"?<form className="expense-editor" onSubmit={saveInventory}><label className="field-group"><span>Unit or shared</span><select name="unitId"><option value="">Shared</option>{units.map((unit)=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label className="field-group"><span>Guest-supply value</span><input name="value" type="number" min="0" required/></label><label className="field-group"><span>Notes</span><textarea name="notes"/></label><button className="primary-button">Save inventory value</button></form>:<form className="expense-editor" onSubmit={saveBalance}><label className="field-group"><span>Balance type</span><select name="category">{categories.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="field-group"><span>Unit when applicable</span><select name="unitId"><option value="">Consolidated/shared</option>{units.map((unit)=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label><label className="field-group"><span>Amount</span><input name="amount" type="number" min="0" required/></label><label className="field-group"><span>Notes</span><textarea name="notes"/></label><button className="primary-button">Save balance</button></form>}</aside>:null}
  </section>;
}
