import { AlertCircle, BarChart3, RefreshCw } from "lucide-react";
import { useCallback,useEffect,useState } from "react";
import type { FinancialReport } from "../../domain/accounting";
import { IPC_CHANNELS } from "../../shared/ipc";
import { RatioTable } from "../components/RatioTable";
import { ReportTable } from "../components/ReportTable";

type View="overview"|"income"|"balance"|"cash-flow"|"break-even"|"ratios";
const monthNow=()=>new Date().toISOString().slice(0,7),formatUgx=(value:number)=>`UGX ${new Intl.NumberFormat("en-UG").format(value)}`;
export function ReportsScreen(){const[month,setMonth]=useState(monthNow);const[view,setView]=useState<View>("overview");const[report,setReport]=useState<FinancialReport|null>(null);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setError(null);const result=await window.stayBooks.invoke(IPC_CHANNELS.REPORT_MONTHLY,{month});if(!result.ok)return setError(result.message);setReport(result.data);},[month]);useEffect(()=>{void load();},[load]);
 const income=report?.incomeStatement,balance=report?.balanceSheet,cash=report?.cashFlow;
 return <section className="reports-screen"><header className="payments-header"><div><h1>Reports</h1><p>Statements, cash flow, break-even, and financial ratios.</p></div><div><label className="month-control"><span>Month</span><input type="month" value={month} onChange={(event)=>setMonth(event.target.value)}/></label><button className="icon-button" aria-label="Refresh reports" onClick={()=>void load()}><RefreshCw size={17}/></button></div></header>
 <nav className="section-tabs report-tabs" aria-label="Report views">{(["overview","income","balance","cash-flow","break-even","ratios"] as const).map((item)=><button data-active={view===item} key={item} onClick={()=>setView(item)}>{item==="cash-flow"?"Cash Flow":item==="break-even"?"Break-Even":item[0].toUpperCase()+item.slice(1)}</button>)}</nav>{error?<p className="form-alert">{error}</p>:null}
 {!report?<div className="statement-loading">Loading reports</div>:view==="overview"?<><div className="report-kpis"><div><span>Revenue</span><strong>{formatUgx(income!.revenue)}</strong></div><div><span>Net income</span><strong>{formatUgx(income!.netIncome)}</strong></div><div><span>Closing cash</span><strong>{formatUgx(cash!.closingCash)}</strong></div><div><span>Balance check</span><strong className={balance!.difference===0?"positive":"negative"}>{balance!.difference===0?"Balanced":formatUgx(Math.abs(balance!.difference))}</strong></div></div><div className="report-overview"><ReportTable title="Income summary" rows={[{label:"Revenue",value:income!.revenue},{label:"Expenses",value:income!.purchases+income!.operatingExpenses+income!.financialExpenses+income!.taxExpense},{label:"Net income",value:income!.netIncome,emphasis:true}]}/><ReportTable title="Balance summary" rows={[{label:"Assets",value:balance!.totalAssets},{label:"Liabilities",value:balance!.totalLiabilities},{label:"Equity",value:balance!.equity},{label:"Liabilities and equity",value:balance!.totalLiabilitiesAndEquity,emphasis:true}]}/></div></>:view==="income"?<ReportTable title="Detailed income statement" rows={[{label:"Sales",value:income!.revenue},{label:"Purchases",value:-income!.purchases},{label:"Gross profit",value:income!.grossProfit,emphasis:true},{label:"Operating expenses",value:-income!.operatingExpenses},{label:"Financial expenses",value:-income!.financialExpenses},{label:"Profit before tax",value:income!.profitBeforeTax,emphasis:true},{label:"Tax expense",value:-income!.taxExpense},{label:"Net income",value:income!.netIncome,emphasis:true}]}/>:view==="balance"?<ReportTable title="Detailed balance sheet" rows={[{label:"Current assets",value:balance!.currentAssets},{label:"Fixed and long-term assets",value:balance!.fixedAssets},{label:"Total assets",value:balance!.totalAssets,emphasis:true},{label:"Current liabilities",value:balance!.currentLiabilities},{label:"Non-current liabilities",value:balance!.nonCurrentLiabilities},{label:"Equity",value:balance!.equity},{label:"Liabilities and equity",value:balance!.totalLiabilitiesAndEquity,emphasis:true}]}/>:view==="cash-flow"?<ReportTable title="Cash flow statement" rows={[{label:"Opening cash",value:cash!.openingCash},{label:"Cash received",value:cash!.cashReceipts},{label:"Cash paid",value:-cash!.cashPayments},{label:"Net cash movement",value:cash!.netChange,emphasis:true},{label:"Closing cash",value:cash!.closingCash,emphasis:true}]}/>:view==="break-even"?<section className="break-even-panel"><BarChart3 size={24}/><h2>Break-even revenue</h2>{report.breakEven.state==="available"?<strong>{formatUgx(Math.round(report.breakEven.value))}</strong>:<div className="metric-unavailable"><AlertCircle size={17}/><span>Not available · {report.breakEven.reason}</span></div>}</section>:<RatioTable ratios={report.ratios}/>}</section>;
}
